export const CLASH_ROYALE_CARDS = [

    // --- Campeones (8) ---

    { id: 2, name: "Monje", imageUrl: "https://temp-cr-image-url.com/monk.png", elixir: 5, rarity: "Campeón", type: "Tropa" },
    { id: 3, name: "Reina Arquera", imageUrl: "https://temp-cr-image-url.com/archer_queen.png", elixir: 5, rarity: "Campeón", type: "Tropa" },
    { id: 4, name: "Gran Minero", imageUrl: "https://temp-cr-image-url.com/mighty_miner.png", elixir: 4, rarity: "Campeón", type: "Tropa" },
    { id: 5, name: "Caballero Dorado", imageUrl: "https://temp-cr-image-url.com/golden_knight.png", elixir: 4, rarity: "Campeón", type: "Tropa" },
    { id: 6, name: "Rey Esqueleto", imageUrl: "https://temp-cr-image-url.com/skeleton_king.png", elixir: 4, rarity: "Campeón", type: "Tropa" },
    { id: 7, name: "Príncipito", imageUrl: "https://temp-cr-image-url.com/little_prince.png", elixir: 3, rarity: "Campeón", type: "Tropa" },
    { id: 8, name: "Bandida Lider", imageUrl: "https://temp-cr-image-url.com/little_prince.png", elixir: 6, rarity: "Campeón", type: "Tropa" },
		{ id: 9, name: "Duendenstein", imageUrl: "https://temp-cr-image-url.com/goblinstein.png", elixir: 5, rarity: "Campeón", type: "Tropa" },
    
    // --- Legendarias (21) ---

    { id: 10, name: "Sabueso de Lava", imageUrl: "https://temp-cr-image-url.com/lava_hound.png", elixir: 7, rarity: "Legendaria", type: "Tropa" },
    { id: 11, name: "Megacaballero", imageUrl: "https://temp-cr-image-url.com/mega_knight.png", elixir: 7, rarity: "Legendaria", type: "Tropa" },
    { id: 12, name: "Emperatriz Espiritual", imageUrl: "https://temp-cr-image-url.com/mega_knight.png", elixir: 6, rarity: "Legendaria", type: "Tropa" },
    { id: 13, name: "Chispitas", imageUrl: "https://temp-cr-image-url.com/sparky.png", elixir: 6, rarity: "Legendaria", type: "Tropa" },
    { id: 14, name: "Máquina Duende", imageUrl: "https://temp-cr-image-url.com/flying_machine.png", elixir: 5, rarity: "Legendaria", type: "Tropa" },
    { id: 15, name: "Cementerio", imageUrl: "https://temp-cr-image-url.com/graveyard.png", elixir: 5, rarity: "Legendaria", type: "Hechizo" },
    { id: 16, name: "Montacarneros", imageUrl: "https://temp-cr-image-url.com/electro_dragon.png", elixir: 5, rarity: "Legendaria", type: "Tropa" },
    { id: 17, name: "Bruja Madre", imageUrl: "https://temp-cr-image-url.com/dark_electro_wizard.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 18, name: "Bruja Nocturna", imageUrl: "https://temp-cr-image-url.com/night_witch.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 19, name: "Leñador", imageUrl: "https://temp-cr-image-url.com/lumberjack.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 20, name: "Arquero Mágico", imageUrl: "https://temp-cr-image-url.com/electro_giant.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 21, name: "Fénix", imageUrl: "https://temp-cr-image-url.com/phoenix.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 22, name: "Mago Eléctrico", imageUrl: "https://temp-cr-image-url.com/electro_wizard.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 23, name: "Dragón Infernal", imageUrl: "https://temp-cr-image-url.com/bomb_tower.png", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 24, name: "Pescador", imageUrl: "https://temp-cr-image-url.com/fisherman.png", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 25, name: "Bandida", imageUrl: "https://temp-cr-image-url.com/bandit.png", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 26, name: "Fantasma Real", imageUrl: "https://temp-cr-image-url.com/royal_ghost.png", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 27, name: "Mago de Hielo", imageUrl: "https://temp-cr-image-url.com/ice_wizard.png", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 28, name: "Minero", imageUrl: "https://temp-cr-image-url.com/miner.png", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 29, name: "Princesa", imageUrl: "https://temp-cr-image-url.com/princess.png", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 30, name: "Tronco", imageUrl: "https://temp-cr-image-url.com/the_log.png", elixir: 2, rarity: "Legendaria", type: "Hechizo" },

    // --- Épicas (33) ---

    { id: 31, name: "Gólem", imageUrl: "https://temp-cr-image-url.com/golem.png", elixir: 8, rarity: "Épica", type: "Tropa" },
    { id: 32, name: "Gigante Eléctrico", imageUrl: "https://temp-cr-image-url.com/electro_giant.png", elixir: 7, rarity: "Épica", type: "Tropa" },
    { id: 33, name: "P.E.K.K.A.", imageUrl: "https://temp-cr-image-url.com/pekka.png", elixir: 7, rarity: "Épica", type: "Tropa" },
    { id: 34, name: "Ballesta", imageUrl: "https://temp-cr-image-url.com/xbow.png", elixir: 6, rarity: "Épica", type: "Estructura" },
    { id: 35, name: "Duende Gigante", imageUrl: "https://temp-cr-image-url.com/goblin_giant.png", elixir: 6, rarity: "Épica", type: "Tropa" },
    { id: 36, name: "Rayo", imageUrl: "https://temp-cr-image-url.com/rocket.png", elixir: 6, rarity: "Épica", type: "Hechizo" },
    { id: 37, name: "Gigante Esqueleto", imageUrl: "https://temp-cr-image-url.com/giant_skeleton.png", elixir: 6, rarity: "Épica", type: "Tropa" },
    { id: 38, name: "Globo", imageUrl: "https://temp-cr-image-url.com/giant.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 39, name: "Cañón con Ruedas", imageUrl: "https://temp-cr-image-url.com/phoenix_egg.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 40, name: "Verdugo", imageUrl: "https://temp-cr-image-url.com/executioner.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 41, name: "Lanzarrocas", imageUrl: "https://temp-cr-image-url.com/bowler.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 42, name: "Dragón Eléctrico", imageUrl: "https://temp-cr-image-url.com/electro_dragon.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 43, name: "Príncipe", imageUrl: "https://temp-cr-image-url.com/prince.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 44, name: "Bruja", imageUrl: "https://temp-cr-image-url.com/witch.png", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 45, name: "Excavadora de duendes", imageUrl: "https://temp-cr-image-url.com/skeleton_dragon.png", elixir: 4, rarity: "Épica", type: "Estructura" },
    { id: 46, name: "Cazador", imageUrl: "https://temp-cr-image-url.com/goblin_barrel.png", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 47, name: "Bebé Dragón", imageUrl: "https://temp-cr-image-url.com/baby_dragon.png", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 48, name: "Veneno", imageUrl: "https://temp-cr-image-url.com/poison.png", elixir: 4, rarity: "Épica", type: "Hechizo" },
    { id: 49, name: "Gigante Rúnica", imageUrl: "https://temp-cr-image-url.com/lightning.png", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 50, name: "Hielo", imageUrl: "https://temp-cr-image-url.com/freeze.png", elixir: 4, rarity: "Épica", type: "Hechizo" },
    { id: 51, name: "Príncipe Oscuro", imageUrl: "https://temp-cr-image-url.com/dark_prince.png", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 52, name: "Vacío", imageUrl: "https://temp-cr-image-url.com/goblin_cage.png", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 53, name: "Tornado", imageUrl: "https://temp-cr-image-url.com/tornado.png", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 54, name: "Clon", imageUrl: "https://temp-cr-image-url.com/tornado.png", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 55, name: "Enredadera", imageUrl: "https://temp-cr-image-url.com/tornado.png", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 56, name: "Barril de Duendes", imageUrl: "https://temp-cr-image-url.com/goblin_barrel.png", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 57, name: "Guardias", imageUrl: "https://temp-cr-image-url.com/goblin_barrel.png", elixir: 3, rarity: "Épica", type: "Tropa" },
    { id: 58, name: "Ejército de Esqueletos", imageUrl: "https://temp-cr-image-url.com/skeleton_army.png", elixir: 3, rarity: "Épica", type: "Tropa" },
    { id: 59, name: "Maldición Duende", imageUrl: "https://temp-cr-image-url.com/goblin_barrel.png", elixir: 2, rarity: "Épica", type: "Hechizo" },
    { id: 60, name: "Furia", imageUrl: "https://temp-cr-image-url.com/rage.png", elixir: 2, rarity: "Épica", type: "Hechizo" },
    { id: 61, name: "Rompemuros", imageUrl: "https://temp-cr-image-url.com/rage.png", elixir: 2, rarity: "Épica", type: "Tropa" },
    { id: 62, name: "Barril de Bárbaro", imageUrl: "https://temp-cr-image-url.com/barbarian_barrel.png", elixir: 2, rarity: "Épica", type: "Hechizo" },
    { id: 63, name: "Espejo", imageUrl: "https://temp-cr-image-url.com/mirror.png", elixir: 0, rarity: "Épica", type: "Hechizo" },

    // --- Especiales (30) ---

    { id: 64, name: "Trio de Mosqueteras", imageUrl: "https://temp-cr-image-url.com/three_musketeers.png", elixir: 9, rarity: "Especial", type: "Tropa" },
    { id: 65, name: "Recolector de Elixir", imageUrl: "https://temp-cr-image-url.com/elixir_collector.png", elixir: 6, rarity: "Especial", type: "Estructura" },
    { id: 66, name: "Choza de Bárbaros", imageUrl: "https://temp-cr-image-url.com/barbarian_hut.png", elixir: 6, rarity: "Especial", type: "Estructura" },
    { id: 67, name: "Cohete", imageUrl: "https://temp-cr-image-url.com/cannon_cart.png", elixir: 6, rarity: "Especial", type: "Hechizo" },
    { id: 68, name: "Puerco Reales", imageUrl: "https://temp-cr-image-url.com/royal_hogs.png", elixir: 5, rarity: "Especial", type: "Tropa" },
    { id: 69, name: "Torre Infernal", imageUrl: "https://temp-cr-image-url.com/inferno_tower.png", elixir: 5, rarity: "Especial", type: "Estructura" },
    { id: 70, name: "Mago", imageUrl: "https://temp-cr-image-url.com/wizard.png", elixir: 5, rarity: "Especial", type: "Tropa" },
    { id: 71, name: "Gigante", imageUrl: "https://temp-cr-image-url.com/giant.png", elixir: 5, rarity: "Especial", type: "Tropa" },
    { id: 72, name: "Demoledor Duende", imageUrl: "https://temp-cr-image-url.com/guards.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 73, name: "Horno", imageUrl: "https://temp-cr-image-url.com/furnace.png", elixir: 4, rarity: "Especial", type: "Tropa" },
		{ id: 74, name: "Electrocutadores", imageUrl: "https://temp-cr-image-url.com/barbarian_barrel.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 75, name: "Curandera de Batalla", imageUrl: "https://temp-cr-image-url.com/battle_healer.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 76, name: "Máquina Voladora", imageUrl: "https://temp-cr-image-url.com/flying_machine.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 77, name: "Montapuercos", imageUrl: "https://temp-cr-image-url.com/hog_rider.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 78, name: "Torre Bombardera", imageUrl: "https://temp-cr-image-url.com/bomb_tower.png", elixir: 4, rarity: "Especial", type: "Estructura" },
    { id: 79, name: "Ariete de Batalla", imageUrl: "https://temp-cr-image-url.com/battle_ram.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 80, name: "Valquiria", imageUrl: "https://temp-cr-image-url.com/valkyrie.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 81, name: "Bola de Fuego", imageUrl: "https://temp-cr-image-url.com/fireball.png", elixir: 4, rarity: "Especial", type: "Hechizo" },
    { id: 82, name: "Jaula del Forzudo", imageUrl: "https://temp-cr-image-url.com/fireball.png", elixir: 4, rarity: "Especial", type: "Estructura" },
    { id: 83, name: "Choza de Duendes", imageUrl: "https://temp-cr-image-url.com/goblin_hut.png", elixir: 4, rarity: "Especial", type: "Estructura" },
    { id: 84, name: "Mini P.E.K.K.A.", imageUrl: "https://temp-cr-image-url.com/mini_pekka.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 85, name: "Mosquetera", imageUrl: "https://temp-cr-image-url.com/musketeer.png", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 86, name: "Gólem de Elixir", imageUrl: "https://temp-cr-image-url.com/musketeer.png", elixir: 3, rarity: "Especial", type: "Tropa" },
    { id: 87, name: "Terremoto", imageUrl: "https://temp-cr-image-url.com/earthquake.png", elixir: 3, rarity: "Especial", type: "Hechizo" },
    { id: 88, name: "Duende Lanzadardos", imageUrl: "https://temp-cr-image-url.com/dart_goblin.png", elixir: 3, rarity: "Especial", type: "Tropa" },
    { id: 89, name: "Megaesbirro", imageUrl: "https://temp-cr-image-url.com/barbarians.png", elixir: 3, rarity: "Especial", type: "Tropa" },
    { id: 90, name: "Lápida", imageUrl: "https://temp-cr-image-url.com/mortar.png", elixir: 3, rarity: "Especial", type: "Estructura" },
    { id: 91, name: "Arbusto Sospechoso", imageUrl: "https://temp-cr-image-url.com/mortar.png", elixir: 2, rarity: "Especial", type: "Tropa" },
    { id: 92, name: "Golem de Hielo", imageUrl: "https://temp-cr-image-url.com/ice_golem.png", elixir: 2, rarity: "Especial", type: "Tropa" },
    { id: 93, name: "Espíritu Sanador", imageUrl: "https://temp-cr-image-url.com/heal_spirit.png", elixir: 1, rarity: "Especial", type: "Tropa" },
    
    // --- Comunes (29) ---
    { id: 94, name: "Reclutas Reales", imageUrl: "https://temp-cr-image-url.com/royal_recruits.png", elixir: 7, rarity: "Común", type: "Tropa" },
    { id: 95, name: "Bárbaros de Élite", imageUrl: "https://temp-cr-image-url.com/royal_recruits.png", elixir: 6, rarity: "Común", type: "Tropa" },
    { id: 96, name: "Gigante Noble", imageUrl: "https://temp-cr-image-url.com/royal_recruits.png", elixir: 6, rarity: "Común", type: "Tropa" },
    { id: 97, name: "Pillos", imageUrl: "https://temp-cr-image-url.com/royal_recruits.png", elixir: 5, rarity: "Común", type: "Tropa" },
    { id: 98, name: "Horda de Esbirros", imageUrl: "https://temp-cr-image-url.com/minion_horde.png", elixir: 5, rarity: "Común", type: "Tropa" },
    { id: 99, name: "Bárbaros", imageUrl: "https://temp-cr-image-url.com/barbarians.png", elixir: 5, rarity: "Común", type: "Tropa" },
    { id: 100, name: "Torre Tesla", imageUrl: "https://temp-cr-image-url.com/tesla.png", elixir: 4, rarity: "Común", type: "Estructura" },
    { id: 101, name: "Mortero", imageUrl: "https://temp-cr-image-url.com/tesla.png", elixir: 4, rarity: "Común", type: "Estructura" },
    { id: 102, name: "Dragones Esqueleto", imageUrl: "https://temp-cr-image-url.com/goblin_demolisher.png", elixir: 4, rarity: "Común", type: "Tropa" },
    { id: 103, name: "Paquete Real", imageUrl: "https://temp-cr-image-url.com/zap.png", elixir: 3, rarity: "Común", type: "Hechizo" },
    { id: 104, name: "Lanzafuegos", imageUrl: "https://temp-cr-image-url.com/goblin_demolisher.png", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 105, name: "Barril de Esqueletos", imageUrl: "https://temp-cr-image-url.com/barbarian_barrel.png", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 106, name: "Pandilla de Duendes", imageUrl: "https://temp-cr-image-url.com/goblin_gang.png", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 107, name: "Cañón", imageUrl: "https://temp-cr-image-url.com/cannon.png", elixir: 3, rarity: "Común", type: "Estructura" },
    { id: 108, name: "Flechas", imageUrl: "https://temp-cr-image-url.com/arrows.png", elixir: 3, rarity: "Común", type: "Hechizo" },
    { id: 109, name: "Esbirros", imageUrl: "https://temp-cr-image-url.com/minions.png", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 110, name: "Arqueras", imageUrl: "https://temp-cr-image-url.com/archers.png", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 111, name: "Caballero", imageUrl: "https://temp-cr-image-url.com/archers.png", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 112, name: "Berserker", imageUrl: "https://temp-cr-image-url.com/archers.png", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 113, name: "Bola de Nieve", imageUrl: "https://temp-cr-image-url.com/giant_snowball.png", elixir: 2, rarity: "Común", type: "Hechizo" },
    { id: 114, name: "Descarga", imageUrl: "https://temp-cr-image-url.com/zap.png", elixir: 2, rarity: "Común", type: "Hechizo" },
    { id: 115, name: "Murcielagos", imageUrl: "https://temp-cr-image-url.com/goblin_demolisher.png", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 116, name: "Bombardero", imageUrl: "https://temp-cr-image-url.com/goblin_demolisher.png", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 117, name: "Duendes con Lanza", imageUrl: "https://temp-cr-image-url.com/spear_goblins.png", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 118, name: "Duendes", imageUrl: "https://temp-cr-image-url.com/goblins.png", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 119, name: "Espíritu de Hielo", imageUrl: "https://temp-cr-image-url.com/ice_spirit.png", elixir: 1, rarity: "Común", type: "Tropa" },
    { id: 120, name: "Espíritu Eléctrico", imageUrl: "https://temp-cr-image-url.com/electro_spirit.png", elixir: 1, rarity: "Común", type: "Tropa" },
    { id: 121, name: "Espíritu de Fuego", imageUrl: "https://temp-cr-image-url.com/electro_spirit.png", elixir: 1, rarity: "Común", type: "Tropa" },
    { id: 122, name: "Esqueletos", imageUrl: "https://temp-cr-image-url.com/skeletons.png", elixir: 1, rarity: "Común", type: "Tropa" },
		
    // --- Tropa de Torre (4) ---

    { id: 123, name: "Princesa de Torre", imageUrl: "https://temp-cr-image-url.com/tower_princess.png", elixir: 0, rarity: "Común", type: "Tropa de Torre" },
    { id: 124, name: "Cocinero Real", imageUrl: "https://temp-cr-image-url.com/royal_chef.png", elixir: 0, rarity: "Legendaria", type: "Tropa de Torre" },
    { id: 125, name: "Duquesa de Dagas", imageUrl: "https://temp-cr-image-url.com/royal_chef.png", elixir: 0, rarity: "Legendaria", type: "Tropa de Torre" },
    { id: 126, name: "Cañonero", imageUrl: "https://temp-cr-image-url.com/royal_chef.png", elixir: 0, rarity: "Épica", type: "Tropa de Torre" },
];

export const CARD_BACK_IMAGE_URL = "https://placehold.co/100x120/303030/ffffff?text=CR+Card";