export const CLASH_ROYALE_CARDS = [

    // --- Campeones (8) ---

    { id: 2, name: "Monje", imageUrl: "/ImagenesCards/Campeones/MonkCard.webp", elixir: 5, rarity: "Campeón", type: "Tropa" },
    { id: 3, name: "Reina Arquera", imageUrl: "/ImagenesCards/Campeones/ArcherQueenCard.webp", elixir: 5, rarity: "Campeón", type: "Tropa" },
    { id: 4, name: "Gran Minero", imageUrl: "/ImagenesCards/Campeones/MightyMinerCard.webp", elixir: 4, rarity: "Campeón", type: "Tropa" },
    { id: 5, name: "Caballero Dorado", imageUrl: "/ImagenesCards/Campeones/GoldenKnightCard.webp", elixir: 4, rarity: "Campeón", type: "Tropa" },
    { id: 6, name: "Rey Esqueleto", imageUrl: "/ImagenesCards/Campeones/SkeletonKingCard.webp", elixir: 4, rarity: "Campeón", type: "Tropa" },
    { id: 7, name: "Príncipito", imageUrl: "/ImagenesCards/Campeones/LittlePrinceCard.webp", elixir: 3, rarity: "Campeón", type: "Tropa" },
    { id: 8, name: "Bandida Lider", imageUrl: "/ImagenesCards/Campeones/BossBanditCard.webp", elixir: 6, rarity: "Campeón", type: "Tropa" },
		{ id: 9, name: "Duendenstein", imageUrl: "/ImagenesCards/Campeones/GoblinsteinCard.webp", elixir: 5, rarity: "Campeón", type: "Tropa" },
    
    // --- Legendarias (21) ---

    { id: 10, name: "Sabueso de Lava", imageUrl: "/ImagenesCards/Legendarias/LavaHoundCard.webp", elixir: 7, rarity: "Legendaria", type: "Tropa" },
    { id: 11, name: "Megacaballero", imageUrl: "/ImagenesCards/Legendarias/MegaKnightCard.webp", elixir: 7, rarity: "Legendaria", type: "Tropa" },
    { id: 12, name: "Emperatriz Espiritual", imageUrl: "/ImagenesCards/Legendarias/SpiritEmpressCard.webp", elixir: 6, rarity: "Legendaria", type: "Tropa" },
    { id: 13, name: "Chispitas", imageUrl: "/ImagenesCards/Legendarias/SparkyCard.webp", elixir: 6, rarity: "Legendaria", type: "Tropa" },
    { id: 14, name: "Máquina Duende", imageUrl: "/ImagenesCards/Legendarias/GoblinMachineCard.webp", elixir: 5, rarity: "Legendaria", type: "Tropa" },
    { id: 15, name: "Cementerio", imageUrl: "/ImagenesCards/Legendarias/GraveyardCard.webp", elixir: 5, rarity: "Legendaria", type: "Hechizo" },
    { id: 16, name: "Montacarneros", imageUrl: "/ImagenesCards/Legendarias/RamRiderCard.webp", elixir: 5, rarity: "Legendaria", type: "Tropa" },
    { id: 17, name: "Bruja Madre", imageUrl: "/ImagenesCards/Legendarias/MotherWitchCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 18, name: "Bruja Nocturna", imageUrl: "/ImagenesCards/Legendarias/NightWitchCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 19, name: "Leñador", imageUrl: "/ImagenesCards/Legendarias/LumberjackCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 20, name: "Arquero Mágico", imageUrl: "/ImagenesCards/Legendarias/MagicArcherCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 21, name: "Fénix", imageUrl: "/ImagenesCards/Legendarias/PhoenixCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 22, name: "Mago Eléctrico", imageUrl: "/ImagenesCards/Legendarias/ElectroWizardCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 23, name: "Dragón Infernal", imageUrl: "/ImagenesCards/Legendarias/InfernoDragonCard.webp", elixir: 4, rarity: "Legendaria", type: "Tropa" },
    { id: 24, name: "Pescador", imageUrl: "/ImagenesCards/Legendarias/FishermanCard.webp", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 25, name: "Bandida", imageUrl: "/ImagenesCards/Legendarias/BanditCard.webp", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 26, name: "Fantasma Real", imageUrl: "/ImagenesCards/Legendarias/RoyalGhostCard.webp", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 27, name: "Mago de Hielo", imageUrl: "/ImagenesCards/Legendarias/IceWizardCard.webp", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 28, name: "Minero", imageUrl: "/ImagenesCards/Legendarias/MinerCard.webp", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 29, name: "Princesa", imageUrl: "/ImagenesCards/Legendarias/PrincessCard.webp", elixir: 3, rarity: "Legendaria", type: "Tropa" },
    { id: 30, name: "Tronco", imageUrl: "/ImagenesCards/Legendarias/TheLogCard.webp", elixir: 2, rarity: "Legendaria", type: "Hechizo" },

    // --- Épicas (33) ---

    { id: 31, name: "Gólem", imageUrl: "/ImagenesCards/Epicas/GolemCard.webp", elixir: 8, rarity: "Épica", type: "Tropa" },
    { id: 32, name: "Gigante Eléctrico", imageUrl: "/ImagenesCards/Epicas/ElectroGiantCard.webp", elixir: 7, rarity: "Épica", type: "Tropa" },
    { id: 33, name: "P.E.K.K.A.", imageUrl: "/ImagenesCards/Epicas/PEKKACard.webp", elixir: 7, rarity: "Épica", type: "Tropa" },
    { id: 34, name: "Ballesta", imageUrl: "/ImagenesCards/Epicas/X-bowCard.png", elixir: 6, rarity: "Épica", type: "Estructura" },
    { id: 35, name: "Duende Gigante", imageUrl: "/ImagenesCards/Epicas/GoblinGiantCard.webp", elixir: 6, rarity: "Épica", type: "Tropa" },
    { id: 36, name: "Rayo", imageUrl: "/ImagenesCards/Epicas/LightningCard.webp", elixir: 6, rarity: "Épica", type: "Hechizo" },
    { id: 37, name: "Gigante Esqueleto", imageUrl: "/ImagenesCards/Epicas/GiantSkeletonCard.webp", elixir: 6, rarity: "Épica", type: "Tropa" },
    { id: 38, name: "Globo", imageUrl: "/ImagenesCards/Epicas/BalloonCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 39, name: "Cañón con Ruedas", imageUrl: "/ImagenesCards/Epicas/CannonCartCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 40, name: "Verdugo", imageUrl: "/ImagenesCards/Epicas/ExecutionerCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 41, name: "Lanzarrocas", imageUrl: "/ImagenesCards/Epicas/BowlerCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 42, name: "Dragón Eléctrico", imageUrl: "/ImagenesCards/Epicas/ElectroDragonCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 43, name: "Príncipe", imageUrl: "/ImagenesCards/Epicas/PrinceCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 44, name: "Bruja", imageUrl: "/ImagenesCards/Epicas/WitchCard.webp", elixir: 5, rarity: "Épica", type: "Tropa" },
    { id: 45, name: "Excavadora de duendes", imageUrl: "/ImagenesCards/Epicas/GoblinDrillCard.webp", elixir: 4, rarity: "Épica", type: "Estructura" },
    { id: 46, name: "Cazador", imageUrl: "/ImagenesCards/Epicas/HunterCard.webp", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 47, name: "Bebé Dragón", imageUrl: "/ImagenesCards/Epicas/BabyDragonCard.webp", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 48, name: "Veneno", imageUrl: "/ImagenesCards/Epicas/PoisonCard.webp", elixir: 4, rarity: "Épica", type: "Hechizo" },
    { id: 49, name: "Gigante Rúnica", imageUrl: "/ImagenesCards/Epicas/RuneGiantCard.webp", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 50, name: "Hielo", imageUrl: "/ImagenesCards/Epicas/FreezeCard.webp", elixir: 4, rarity: "Épica", type: "Hechizo" },
    { id: 51, name: "Príncipe Oscuro", imageUrl: "/ImagenesCards/Epicas/DarkPrinceCard.webp", elixir: 4, rarity: "Épica", type: "Tropa" },
    { id: 52, name: "Vacío", imageUrl: "/ImagenesCards/Epicas/VoidCard.webp", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 53, name: "Tornado", imageUrl: "/ImagenesCards/Epicas/TornadoCard.webp", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 54, name: "Clon", imageUrl: "/ImagenesCards/Epicas/CloneCard.webp", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 55, name: "Enredadera", imageUrl: "/ImagenesCards/Epicas/VinesCard.webp", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 56, name: "Barril de Duendes", imageUrl: "/ImagenesCards/Epicas/GoblinBarrelCard.webp", elixir: 3, rarity: "Épica", type: "Hechizo" },
    { id: 57, name: "Guardias", imageUrl: "/ImagenesCards/Epicas/GuardsCard.webp", elixir: 3, rarity: "Épica", type: "Tropa" },
    { id: 58, name: "Ejército de Esqueletos", imageUrl: "/ImagenesCards/Epicas/SkeletonArmyCard.webp", elixir: 3, rarity: "Épica", type: "Tropa" },
    { id: 59, name: "Maldición Duende", imageUrl: "/ImagenesCards/Epicas/GoblinCurseCard.webp", elixir: 2, rarity: "Épica", type: "Hechizo" },
    { id: 60, name: "Furia", imageUrl: "/ImagenesCards/Epicas/RageCard.webp", elixir: 2, rarity: "Épica", type: "Hechizo" },
    { id: 61, name: "Rompemuros", imageUrl: "/ImagenesCards/Epicas/WallBreakersCard.webp", elixir: 2, rarity: "Épica", type: "Tropa" },
    { id: 62, name: "Barril de Bárbaro", imageUrl: "/ImagenesCards/Epicas/BarbarianBarrelCard.webp", elixir: 2, rarity: "Épica", type: "Hechizo" },
    { id: 63, name: "Espejo", imageUrl: "/ImagenesCards/Epicas/MirrorCard.webp", elixir: 0, rarity: "Épica", type: "Hechizo" },

    // --- Especiales (30) ---

    { id: 64, name: "Trio de Mosqueteras", imageUrl: "/ImagenesCards/Especiales/ThreeMusketeersCard.webp", elixir: 9, rarity: "Especial", type: "Tropa" },
    { id: 65, name: "Recolector de Elixir", imageUrl: "/ImagenesCards/Especiales/ElixirCollectorCard.webp", elixir: 6, rarity: "Especial", type: "Estructura" },
    { id: 66, name: "Choza de Bárbaros", imageUrl: "/ImagenesCards/Especiales/BarbarianHutCard.webp", elixir: 6, rarity: "Especial", type: "Estructura" },
    { id: 67, name: "Cohete", imageUrl: "/ImagenesCards/Especiales/RocketCard.webp", elixir: 6, rarity: "Especial", type: "Hechizo" },
    { id: 68, name: "Puerco Reales", imageUrl: "/ImagenesCards/Especiales/RoyalHogsCard.webp", elixir: 5, rarity: "Especial", type: "Tropa" },
    { id: 69, name: "Torre Infernal", imageUrl: "/ImagenesCards/Especiales/InfernoTowerCard.webp", elixir: 5, rarity: "Especial", type: "Estructura" },
    { id: 70, name: "Mago", imageUrl: "/ImagenesCards/Especiales/WizardCard.webp", elixir: 5, rarity: "Especial", type: "Tropa" },
    { id: 71, name: "Gigante", imageUrl: "/ImagenesCards/Especiales/GiantCard.webp", elixir: 5, rarity: "Especial", type: "Tropa" },
    { id: 72, name: "Demoledor Duende", imageUrl: "/ImagenesCards/Especiales/GoblinDemolisherCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 73, name: "Horno", imageUrl: "/ImagenesCards/Especiales/FurnaceCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
		{ id: 74, name: "Electrocutadores", imageUrl: "/ImagenesCards/Especiales/ZappiesCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 75, name: "Curandera de Batalla", imageUrl: "/ImagenesCards/Especiales/BattleHealerCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 76, name: "Máquina Voladora", imageUrl: "/ImagenesCards/Especiales/FlyingMachineCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 77, name: "Montapuercos", imageUrl: "/ImagenesCards/Especiales/HogRiderCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 78, name: "Torre Bombardera", imageUrl: "/ImagenesCards/Especiales/BombTowerCard.webp", elixir: 4, rarity: "Especial", type: "Estructura" },
    { id: 79, name: "Ariete de Batalla", imageUrl: "/ImagenesCards/Especiales/BattleRamCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 80, name: "Valquiria", imageUrl: "/ImagenesCards/Especiales/ValkyrieCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 81, name: "Bola de Fuego", imageUrl: "/ImagenesCards/Especiales/FireballCard.webp", elixir: 4, rarity: "Especial", type: "Hechizo" },
    { id: 82, name: "Jaula del Forzudo", imageUrl: "/ImagenesCards/Especiales/GoblinCageCard.webp", elixir: 4, rarity: "Especial", type: "Estructura" },
    { id: 83, name: "Choza de Duendes", imageUrl: "/ImagenesCards/Especiales/GoblinHutCard.webp", elixir: 4, rarity: "Especial", type: "Estructura" },
    { id: 84, name: "Mini P.E.K.K.A.", imageUrl: "/ImagenesCards/Especiales/MiniPEKKACard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 85, name: "Mosquetera", imageUrl: "/ImagenesCards/Especiales/MusketeerCard.webp", elixir: 4, rarity: "Especial", type: "Tropa" },
    { id: 86, name: "Gólem de Elixir", imageUrl: "/ImagenesCards/Especiales/ElixirGolemCard.webp", elixir: 3, rarity: "Especial", type: "Tropa" },
    { id: 87, name: "Terremoto", imageUrl: "/ImagenesCards/Especiales/EarthquakeCard.webp", elixir: 3, rarity: "Especial", type: "Hechizo" },
    { id: 88, name: "Duende Lanzadardos", imageUrl: "/ImagenesCards/Especiales/DartGoblinCard.webp", elixir: 3, rarity: "Especial", type: "Tropa" },
    { id: 89, name: "Megaesbirro", imageUrl: "/ImagenesCards/Especiales/MegaMinionCard.webp", elixir: 3, rarity: "Especial", type: "Tropa" },
    { id: 90, name: "Lápida", imageUrl: "/ImagenesCards/Especiales/TombstoneCard.webp", elixir: 3, rarity: "Especial", type: "Estructura" },
    { id: 91, name: "Arbusto Sospechoso", imageUrl: "/ImagenesCards/Especiales/SuspiciousBushCard.webp", elixir: 2, rarity: "Especial", type: "Tropa" },
    { id: 92, name: "Golem de Hielo", imageUrl: "/ImagenesCards/Especiales/IceGolemCard.webp", elixir: 2, rarity: "Especial", type: "Tropa" },
    { id: 93, name: "Espíritu Sanador", imageUrl: "/ImagenesCards/Especiales/HealSpiritCard.webp", elixir: 1, rarity: "Especial", type: "Tropa" },
    
    // --- Comunes (29) ---

    { id: 94, name: "Reclutas Reales", imageUrl: "/ImagenesCards/Comunes/RoyalRecruitsCard.webp", elixir: 7, rarity: "Común", type: "Tropa" },
    { id: 95, name: "Bárbaros de Élite", imageUrl: "/ImagenesCards/Comunes/EliteBarbariansCard.webp", elixir: 6, rarity: "Común", type: "Tropa" },
    { id: 96, name: "Gigante Noble", imageUrl: "/ImagenesCards/Comunes/RoyalGiantCard.webp", elixir: 6, rarity: "Común", type: "Tropa" },
    { id: 97, name: "Pillos", imageUrl: "/ImagenesCards/Comunes/RascalsCard.webp", elixir: 5, rarity: "Común", type: "Tropa" },
    { id: 98, name: "Horda de Esbirros", imageUrl: "/ImagenesCards/Comunes/MinionHordeCard.webp", elixir: 5, rarity: "Común", type: "Tropa" },
    { id: 99, name: "Bárbaros", imageUrl: "/ImagenesCards/Comunes/BarbariansCard.webp", elixir: 5, rarity: "Común", type: "Tropa" },
    { id: 100, name: "Torre Tesla", imageUrl: "/ImagenesCards/Comunes/TeslaCard.webp", elixir: 4, rarity: "Común", type: "Estructura" },
    { id: 101, name: "Mortero", imageUrl: "/ImagenesCards/Comunes/MortarCard.webp", elixir: 4, rarity: "Común", type: "Estructura" },
    { id: 102, name: "Dragones Esqueleto", imageUrl: "/ImagenesCards/Comunes/SkeletonDragonsCard.webp", elixir: 4, rarity: "Común", type: "Tropa" },
    { id: 103, name: "Paquete Real", imageUrl: "/ImagenesCards/Comunes/RoyalDeliveryCard.webp", elixir: 3, rarity: "Común", type: "Hechizo" },
    { id: 104, name: "Lanzafuegos", imageUrl: "/ImagenesCards/Comunes/FirecrackerCard.webp", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 105, name: "Barril de Esqueletos", imageUrl: "/ImagenesCards/Comunes/SkeletonBarrelCard.webp", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 106, name: "Pandilla de Duendes", imageUrl: "/ImagenesCards/Comunes/GoblinGangCard.webp", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 107, name: "Cañón", imageUrl: "/ImagenesCards/Comunes/CannonCard.webp", elixir: 3, rarity: "Común", type: "Estructura" },
    { id: 108, name: "Flechas", imageUrl: "/ImagenesCards/Comunes/ArrowsCard.webp", elixir: 3, rarity: "Común", type: "Hechizo" },
    { id: 109, name: "Esbirros", imageUrl: "/ImagenesCards/Comunes/MinionsCard.webp", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 110, name: "Arqueras", imageUrl: "/ImagenesCards/Comunes/ArchersCard.webp", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 111, name: "Caballero", imageUrl: "/ImagenesCards/Comunes/KnightCard.webp", elixir: 3, rarity: "Común", type: "Tropa" },
    { id: 112, name: "Berserker", imageUrl: "/ImagenesCards/Comunes/BerserkerCard.png", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 113, name: "Bola de Nieve", imageUrl: "/ImagenesCards/Comunes/GiantSnowballCard.webp", elixir: 2, rarity: "Común", type: "Hechizo" },
    { id: 114, name: "Descarga", imageUrl: "/ImagenesCards/Comunes/ZapCard.webp", elixir: 2, rarity: "Común", type: "Hechizo" },
    { id: 115, name: "Murcielagos", imageUrl: "/ImagenesCards/Comunes/BatsCard.webp", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 116, name: "Bombardero", imageUrl: "/ImagenesCards/Comunes/BomberCard.webp", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 117, name: "Duendes con Lanza", imageUrl: "/ImagenesCards/Comunes/SpearGoblinsCard.webp", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 118, name: "Duendes", imageUrl: "/ImagenesCards/Comunes/GoblinsCard.webp", elixir: 2, rarity: "Común", type: "Tropa" },
    { id: 119, name: "Espíritu de Hielo", imageUrl: "/ImagenesCards/Comunes/IceSpiritCard.webp", elixir: 1, rarity: "Común", type: "Tropa" },
    { id: 120, name: "Espíritu Eléctrico", imageUrl: "/ImagenesCards/Comunes/ElectroSpiritCard.webp", elixir: 1, rarity: "Común", type: "Tropa" },
    { id: 121, name: "Espíritu de Fuego", imageUrl: "/ImagenesCards/Comunes/FireSpiritsCard.webp", elixir: 1, rarity: "Común", type: "Tropa" },
    { id: 122, name: "Esqueletos", imageUrl: "/ImagenesCards/Comunes/SkeletonsCard.webp", elixir: 1, rarity: "Común", type: "Tropa" },
		
    // --- Tropa de Torre (4) ---

    { id: 123, name: "Princesa de Torre", imageUrl: "/ImagenesCards/TropaDeTorre/TowerPrincessCard.webp", elixir: 0, rarity: "Común", type: "Tropa de Torre" },
    { id: 124, name: "Cocinero Real", imageUrl: "/ImagenesCards/TropaDeTorre/RoyalChefCard.webp", elixir: 0, rarity: "Legendaria", type: "Tropa de Torre" },
    { id: 125, name: "Duquesa de Dagas", imageUrl: "/ImagenesCards/TropaDeTorre/DaggerDuchessCard.webp", elixir: 0, rarity: "Legendaria", type: "Tropa de Torre" },
    { id: 126, name: "Cañonero", imageUrl: "/ImagenesCards/TropaDeTorre/CannoneerCard.webp", elixir: 0, rarity: "Épica", type: "Tropa de Torre" },
];

export const CARD_BACK_IMAGE_URL = "https://placehold.co/100x120/303030/ffffff?text=CR+Card";